name: facipoint_sunmi_printer
description: Flutter wrapper for Sunmi's and Aisino's Android Printer SDK
version: 0.2.2

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  plugin:
    platforms:
      android:
        package: ao.co.atech.dev.facipoint_sunmi_printer
        pluginClass: FaciPointSunmiPrinterPlugin
