name: cartona_sunmi_printer
description: Flutter wrapper for Sunmi's printer SDK
version: 0.1.0

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.cartona_sunmi_printer
        pluginClass: CartonaSunmiPrinterPlugin
